name = "Sanita"
age = 45
lenght = 1.73
is_3plus_card = True
is_car_licence = True
is_man = False
grandchilds = None
print (type(name))
print (type(age))
print (type(lenght))
print (type(age) ==type(lenght))
children = 3
print (type(age) == type(children))
print (bool (name))
print (bool ([]))
print (bool(None))
print (bool ([]))
print (bool (0))
print (bool ("0"))
print (int ("45"))
print (float ("1.73"))
print (str (45))
print (int (float("1.73")))
print ("Sa" + "nita")
print ("4" + "55")
print (45 - 4) 
print (int("45") + 5)
print (bool(""))
print (False + False)
print (True + True)
print (True + False)
print (True - 2)
print (False + 44)
print (True * 3 - 1)
print (True * 3 - 1)
print (8 * True / 4)
print (8 * True / (4 - 2))
print (1e3)
print (int(1e3))
print (2e4)
print (1 + 2 == 3)
print (0.1 + 0.2 == 0.3)
print (0.1 + 0.2)
from decimal import Decimal
a = Decimal("0.1")
b = Decimal("0.2")
print (a + b)
print (round(6.6))
print (round(6.4))
print (round(6.5))
print (round(7.5))